import type { LucideProps } from "lucide-react";
import {
  BadgeCheck,
  Banknote,
  Bath,
  Briefcase,
  Building,
  BookOpen,
  Building2,
  CalendarCheck2,
  CalendarClock,
  CloudRain,
  Droplet,
  Droplets,
  Eye,
  Gauge,
  Fence,
  FileText,
  GitBranch,
  GraduationCap,
  Grid3x3,
  Hammer,
  HardHat,
  Home,
  House,
  KeyRound,
  KeySquare,
  Landmark,
  LayoutGrid,
  MapPin,
  MessageSquare,
  PaintRoller,
  RefreshCw,
  Ruler,
  Search,
  ShieldCheck,
  ShowerHead,
  Target,
  ThumbsUp,
  Timer,
  TrendingUp,
  Truck,
  Users,
  Waves,
  Wrench,
  Zap,
} from "lucide-react";

// Explicit map (rather than `import * as Icons`) so bundlers can tree-shake
// unused icons instead of pulling the entire lucide-react library into
// whatever chunk this file ends up in.
const iconMap = {
  BadgeCheck,
  Banknote,
  Bath,
  Briefcase,
  Building,
  BookOpen,
  Building2,
  CalendarCheck2,
  CalendarClock,
  CloudRain,
  Droplet,
  Droplets,
  Eye,
  Fence,
  FileText,
  GitBranch,
  GraduationCap,
  Grid3x3,
  Hammer,
  HardHat,
  Home,
  House,
  Gauge,
  KeyRound,
  KeySquare,
  Landmark,
  LayoutGrid,
  MapPin,
  MessageSquare,
  PaintRoller,
  RefreshCw,
  Ruler,
  Search,
  ShieldCheck,
  ShowerHead,
  Target,
  ThumbsUp,
  Timer,
  TrendingUp,
  Truck,
  Users,
  Waves,
  Wrench,
  Zap,
} satisfies Record<string, React.ComponentType<LucideProps>>;

export type IconName = keyof typeof iconMap;

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Component = iconMap[name as IconName];
  if (!Component) return null;
  return <Component {...props} />;
}
